using FlowchartNET.Components.Symbols.Data;
using System.Text;

namespace FlowchartNET.Components.CodeGenerators;

internal sealed class LuaCodeGenerator : CodeGenerator
{
    private readonly HashSet<Guid> _visited = [];
    private readonly HashSet<Guid> _symbolsRequiringLabel = [];
    private readonly HashSet<string> _variables = [];

    protected override void GenerateSymbolCode(StringBuilder sb, StartSymbolData startSymbol, IDictionary<Guid, SymbolData> allSymbols)
    {
        sb.AppendLine("-- Generated by Flowchart.NET with goto support (Lua)");
        DetectLabels(allSymbols);
        GenerateSymbolCode(sb, 0, startSymbol, allSymbols);
    }

    private void DetectLabels(IDictionary<Guid, SymbolData> allSymbols)
    {
        var incomingCounts = new Dictionary<Guid, int>();
        foreach (var symbol in allSymbols.Values)
        {
            foreach (var connectedId in symbol.GetConnectedSymbolIds())
            {
                incomingCounts[connectedId] = incomingCounts.GetValueOrDefault(connectedId) + 1;
            }
        }
        foreach (var kvp in incomingCounts)
        {
            if (kvp.Value > 1)
            {
                _symbolsRequiringLabel.Add(kvp.Key);
            }
        }
    }

    private void GenerateSymbolCode(StringBuilder sb, int indent, SymbolData symbol, IDictionary<Guid, SymbolData> allSymbols)
    {
        if (_visited.Contains(symbol.Id))
        {
            if (_symbolsRequiringLabel.Contains(symbol.Id))
            {
                sb.Append(new string(' ', indent * 4));
                sb.AppendLine($"goto {FormatLabel(symbol)}");
            }
            return;
        }

        _visited.Add(symbol.Id);

        if (_symbolsRequiringLabel.Contains(symbol.Id))
        {
            sb.AppendLine($"::{FormatLabel(symbol)}::");
        }

        var indentStr = new string(' ', indent * 4);

        switch (symbol)
        {
            case IOSymbolData ioSymbol:
                GenerateIoCode(sb, ioSymbol, indentStr);
                break;

            case ProcessSymbolData processSymbol:
                if (processSymbol.VariableName is not null)
                {
                    if (_variables.Add(processSymbol.VariableName))
                    {
                        sb.Append(indentStr);
                        sb.Append($"local {processSymbol.VariableName} = ");
                    }
                    else
                    {
                        sb.Append(indentStr);
                        sb.Append($"{processSymbol.VariableName} = ");
                    }
                }
                else
                {
                    sb.Append(indentStr);
                }
                sb.Append(processSymbol.Process);
                sb.AppendLine();
                break;

            case DecisionSymbolData decisionSymbol:
                sb.AppendLine($"{indentStr}if {decisionSymbol.Condition} then");
                foreach (var trueSymbolId in decisionSymbol.TrueSymbols)
                {
                    if (allSymbols.TryGetValue(trueSymbolId, out var trueSymbol))
                    {
                        GenerateSymbolCode(sb, indent + 1, trueSymbol, allSymbols);
                    }
                }
                if (decisionSymbol.FalseSymbols.Count > 0)
                {
                    sb.AppendLine($"{indentStr}else");
                    foreach (var falseSymbolId in decisionSymbol.FalseSymbols)
                    {
                        if (allSymbols.TryGetValue(falseSymbolId, out var falseSymbol))
                        {
                            GenerateSymbolCode(sb, indent + 1, falseSymbol, allSymbols);
                        }
                    }
                }
                sb.AppendLine($"{indentStr}end");

                var nextSymbols = GetCommonNextSymbols(decisionSymbol.TrueSymbols, decisionSymbol.FalseSymbols, allSymbols);
                foreach (var nextSymbol in nextSymbols)
                {
                    GenerateSymbolCode(sb, indent, nextSymbol, allSymbols);
                }
                break;

            case StartSymbolData:
            case EndSymbolData:
                break;

            default:
                sb.AppendLine($"{indentStr}-- Handle other symbol types here");
                break;
        }

        var connectedIds = symbol.GetConnectedSymbolIds().ToList();
        if (symbol is not DecisionSymbolData && connectedIds.Count > 0)
        {
            foreach (var nextId in connectedIds)
            {
                if (allSymbols.TryGetValue(nextId, out var nextSymbol))
                {
                    GenerateSymbolCode(sb, indent, nextSymbol, allSymbols);
                }
            }
        }
    }

    private static IEnumerable<SymbolData> GetCommonNextSymbols(IEnumerable<Guid> trueSymbols, IEnumerable<Guid> falseSymbols, IDictionary<Guid, SymbolData> allSymbols)
    {
        var trueNext = trueSymbols.SelectMany(id => allSymbols[id].GetConnectedSymbolIds()).Distinct();
        var falseNext = falseSymbols.SelectMany(id => allSymbols[id].GetConnectedSymbolIds()).Distinct();
        var commonNextIds = trueNext.Intersect(falseNext);
        return commonNextIds.Select(id => allSymbols[id]);
    }

    private static string FormatLabel(SymbolData symbol)
    {
        var name = symbol.Id.ToString().Replace('-', '_');
        if (char.IsDigit(name[0]))
        {
            name = "_" + name;
        }
        return name;
    }

    private void GenerateIoCode(StringBuilder sb, IOSymbolData symbol, string indentStr)
    {
        if (!string.IsNullOrEmpty(symbol.OutputFormat))
        {
            var outputFormat = string.IsNullOrEmpty(symbol.OutputFormat) ? "{0}" : symbol.OutputFormat;
            // Lua string.format for output
            sb.AppendLine($"{indentStr}print(string.format(\"{outputFormat}\", {symbol.VariableName}))");
            return;
        }

        if (symbol.VariableName is not null)
        {
            if (_variables.Add(symbol.VariableName))
            {
                sb.Append($"{indentStr}local {symbol.VariableName} = ");
            }
            else
            {
                sb.Append($"{indentStr}{symbol.VariableName} = ");
            }
        }
        else
        {
            sb.Append(indentStr);
        }

        sb.AppendLine("io.read()");
    }
}
