using FlowchartNET.Components.Symbols.Data;
using System.Text;

namespace FlowchartNET.Components.CodeGenerators;

internal sealed class LuaCodeGenerator : CodeGenerator
{
    protected override void GenerateSymbolCode(StringBuilder sb, StartSymbolData startSymbol)
    {
        sb.AppendLine("-- Generated by Flowchart.NET");
    }
}
